#!/bin/sh
# Lock the screen. (using aur/i3lock-lixxia-git package)

# -- Take a screenshot, pixelize it, and optionally add a LOCK icon in the middle (then pass -u to i3lock)
scrot /tmp/screen.png
convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png
#[[ -f $1 ]] && convert /tmp/screen.png $1 -gravity center -composite -matte /tmp/screen.png

# -- EXTRA: If we're away, pause stuff.
#music pause
killall ssh-agent

# -- Lock the screen
i3lock --show-failed-attempts --ignore-empty-password --nofork --image=/tmp/screen.png
rm /tmp/screen.png
