#!/bin/sh
# Get the address of the original entrypoint of the specified program(s)
#   Usage: entrypoint <filename...>
#     e.g. entrypoint /usr/bin/ls     # -> 0x00005060
#     e.g. entrypoint /bin/{ls,cat}   # -> 0x00005060 0x00002290
parallel -k rabin2 -e {} ::: "$@" | awk -F'[= \t]+' '/^vaddr/{print $2}'

#---
#for file; do rabin2 -e "$file" | awk -F'[= \t]+' '/^vaddr/{print $2}'; done
