#!/bin/sh
pipe "$@" | perl -MURI::Escape -ne 'print uri_unescape($_)'
#python -c "import urllib, sys; print urllib.unquote(sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()[0:-1])"
#pipe "$@" | sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | xargs echo -e
