#!/bin/sh
case "$1" in
  "")   xbacklight -get;;
  up)   xbacklight -steps 100 -time 500 -inc 15;;
  down) xbacklight -steps 100 -time 500 -dec 15;;
  *)    xbacklight -steps 100 -time 500 -set "$@";;
esac
