#!/bin/sh
# List all the .desktop that belongs to a specified category
#  Usage: desktop-category <category>
#    e.g. desktop-category terminal
grep -liR "Categories=.*$*.*" /usr/share/applications/ | for-each-line basename -as .desktop 2>/dev/null
