#!/bin/sh
# Reload the specified service config.
#   Usage: reload <service...>
#     e.g. reload nginx samba

# Check which service command exist on the system...
for x in systemctl service; do
  if has $x; then
    cmd=$x
    break
  fi
done

# For each service name passed in argument...
for service
do
  case "$cmd" in
    systemctl) RUN_AS_ROOT systemctl reload $service;;   # (e.g. archlinux)
    service)   RUN_AS_ROOT service $service reload;;     # (e.g. debian)
    *)         RUN_AS_ROOT /etc/init.d/$service reload;; # (e.g. gentoo)
  esac
done


