#!/bin/sh
# Align only the N-th instance of a pattern (by default, 1)
#   Usage: align-n [n] <pattern> [file]
if [ $# -eq 0 ];then fail "align: argument 'pattern' missing."; return; fi
if [[ "$1" =~ ^[0-9]+$ ]];then n=$1; shift; fi
regex=$1
file=$2

sed "s/\\t/    /g; s/$regex/ÿ&ÿ/${n:-1}" $file | nodot column -ts 'ÿ' -o ' '

