#!/bin/bash
# Usage: progressbar <percentage> [description] [width] [char_progress] [char_indicator] [char_start] [char_end]
#  (note: `percentage` can be either of 4 forms: 8/12, 0.66, 66, 66%)

# [DEMO MODE] if no argument
if [ -z "$1" ]; then for i in {0..100}; do progressbar $i "Processing DEMO..."; sleep 0.01; done; echo; exit; fi

# -- Read arguments...
percentage=${1%%%}
current_task=$2
width=${3:-50}
char_progress=${4:-=}   # e.g. =, -
char_indicator=${5:->}  # e.g. >, |, //, », ❯, 
char_todo=" "           # e.g. " ", _
char_start=${6:-[}      # e.g. [, (, {, <, ❮, |
char_end=${7:-]}        # e.g. ], ), }, >, ❯, |

# -- Display...
perl -e "  use POSIX;
         \$progress = ($percentage);
         \$progress /= 100.0 if (\$progress >= 1);
         \$done = floor(\$progress*$width);
         \$todo = floor((1-\$progress)*$width);
         \$todo += 1 if(\$done+\$todo < $width);

           print \"\n\".\$done.\" + \".\$todo.\" = \"..\"\n\";

           print \"\r\".(\" \" x ${COLUMNS:-0}).\"\r\";
           print \"  $char_start\".
                   (\"$char_progress\" x \$done).\"$char_indicator\".
                   (\"$char_todo\" x \$todo).
                 \"$char_end \".
                 (\$progress*100).\" %\""

