#!/bin/sh
# Replace the first N occurences of a pattern.
#   Usage: replace-first [n] <pattern> <replacement> [file]
if [ $# -lt 2 ];then fail "replace: argument 'pattern' or argument 'new-text' missing."; return; fi
if [[ "$1" =~ ^[0-9]+$ ]];then n=$1; shift; fi
n=${n:-1}; regex=$1; replace=${2//'/\\'}; file=$3
perl -pe "\$times=$n; s/($regex)/ \$times-- > 0 ? '$replace' : \$1 /eg"
