#!/bin/sh
sudo lshw -short -quiet -c memory | awk '
  /L1 cache/      { l1 = $3 }
  /L2 cache/      { l2 = $3 }
  /L3 cache/      { l3 = $3 }

  END { print "[ L1: "l1" -- L2: "l2" -- L3: "l3" ]" }
'
