#!/bin/sh
# Create or edit a function (using a template).
# Usage: fu <function-to-create-or-edit [...]>

FUNCTIONS_DIR=~/.bin
TEMPLATES_DIR=~/.templates

# -- Create the functions directory if it doesn't exists...
[ -e "$FUNCTIONS_DIR" ] || mkdir -p $FUNCTIONS_DIR/

# -- For each functions in argument, edit/create them...
for func
do
  file="$FUNCTIONS_DIR/$func"
  [ ! -e "$file" ] && cp $TEMPLATES_DIR/shell-script.sh "$file" && chmod +x "$file"
  edit "$file"
done

# -- Relink everything properly...
(cd $FUNCTIONS_DIR; for file in .*/*; do ln -sf $file .; done)
hash -r

