#!/bin/sh
# List the most used C functions in a code directory (e.g. the linux kernel source code)
#   Usage: frequent-c-function-calls [dir]
find "${1:-.}" -type f -exec cat {} \; \
  | ruby -e 'puts STDIN.read.gsub(/\/\*.*?\*\//m, "").gsub(/\/\/.*/, "").gsub(/#ifdef 0\n.*\n#endif/m, "").gsub(/^#.*/, "")' \
  | grep -oP '([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\()' \
  | tr -d ' ' \
  | grep -vP '^(auto|break|case|char|const|continue|default|do|double|else|enum|extern|float|for|goto|if|int|long|register|return|short|signed|sizeof|static|struct|switch|typedef|union|unsigned|void|volatile|while)$' \
  | sort | uniq -c | sort -n
