#!/bin/bash
# Display a table of the 8 original ANSI colors.

echo "      40      41      42      43      44      45      46      47      49   "
for fg in {0..7}; do
  echo -n "3$fg "
  for x in Normal Bold; do
    [ $x = 'Bold' ] && tput bold;
    for bg in {0..7} 8; do
      tput setab $bg
      [ $bg -gt 7 ] && tput op
      tput setaf $fg
      printf " %6s " $x
    done
    echo -en '\e[0m'
    [ $x = 'Normal' ] && echo -en '\n   '
  done
  tput op
  echo
done

