#!/bin/bash
# Display a list of the 256 ANSI color-extension available.
width=${1:-$((${COLUMNS}-6))}

for c in {0..256}
do
  tput setaf $c                 # (set foreground colors)
  printf "%03d: " $c            # print the color code
  tput setab $c                 # (set background colors)
  printf "%${width}s"           # print colored spaces
  tput op                       # (reset colors)
  echo ${1:+-n} " "
done
