#!/bin/sh
# Get github repo statistics from url (open issues, followers, stars, forks)
curl "https://api.github.com/repos/$(github-repo-from-url "$1")" | jq -r ' "Issues: \(.open_issues_count) // Followers: \(.subscribers_count) // Stars: \(.stargazers_count) // Forks: \(.forks_count)" '
