#!/bin/sh
# Stop the specified service.
#   Usage: stop <service...>
#     e.g. stop nginx samba

# Check which service command exist on the system...
for x in systemctl service; do
  if has $x; then
    cmd=$x
    break
  fi
done

# For each service name passed in argument...
for service
do
  case "$cmd" in
    systemctl) RUN_AS_ROOT systemctl stop $service;;   # (e.g. archlinux)
    service)   RUN_AS_ROOT service $service stop;;     # (e.g. debian)
    *)         RUN_AS_ROOT /etc/init.d/$service stop;; # (e.g. gentoo)
  esac
done

